---
on: [push]

jobs:
  build:
    strategy:
      matrix:
        otp: [25, 26]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - run: make all dialyze tests
